"""added user roles

Revision ID: 5c6d92a06ff5
Revises: b309b12e6399
Create Date: 2024-11-11 16:37:52.419658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5c6d92a06ff5'
down_revision: Union[str, None] = 'b309b12e6399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isSuperAdmin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('isClientAdmin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('isClientUser', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'isClientUser')
    op.drop_column('users', 'isClientAdmin')
    op.drop_column('users', 'isSuperAdmin')
    # ### end Alembic commands ###
