"""init

Revision ID: e607ea742197
Revises: 25aea62c09c7
Create Date: 2024-11-11 15:15:12.131353
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e607ea742197'
down_revision: Union[str, None] = '25aea62c09c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alter the 'password' column to INTEGER, with explicit casting
    op.alter_column('users', 'password', 
                    type_=sa.Integer(), 
                    postgresql_using='password::integer')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', type_=sa.String())  # Or sa.Text()

    # ### end Alembic commands ###
